config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  namespace :admin do
    root to: "home#index"
    resources :categories
    resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :position, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image do |att|
    att.variant :thumb, resize_to_limit: [100, 100]
    att.variant :big_thumb, resize_to_limit: [600, 700]
  end

  belongs_to :category

  validates :name, :description, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :phone, presence: true

  enum role: { admin: 'admin', user: 'user' }
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    layout 'admin'

    before_action :authenticate_user!
    before_action :only_admin!

    private

    def only_admin!
      redirect_to root_path unless current_user.admin?
    end
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < BaseController
    before_action :set_category, only: %i[ show edit update destroy ]
  
    # GET /categories or /categories.json
    def index
      @categories = Category.all
    end
  
    # GET /categories/1 or /categories/1.json
    def show; end
  
    # GET /categories/new
    def new
      @category = Category.new
    end
  
    # GET /categories/1/edit
    def edit
    end
  
    # POST /categories or /categories.json
    def create
      @category = Category.new(category_params)
  
      respond_to do |format|
        if @category.save
          format.html { redirect_to admin_categories_path, notice: "Category was successfully created." }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /categories/1 or /categories/1.json
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to admin_categories_path, notice: "Category was successfully updated." }
          format.json { render :show, status: :ok, location: @category }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /categories/1 or /categories/1.json
    def destroy
      @category.destroy
  
      respond_to do |format|
        format.html { redirect_to admin_categories_url, notice: "Category was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def category_params
        params.require(:category).permit(:name, :position)
      end
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < BaseController
    def index
    end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < BaseController
    before_action :set_product, only: %i[ show edit update destroy ]
  
    # GET /products or /products.json
    def index
      @products = Product.all
    end
  
    # GET /products/1 or /products/1.json
    def show; end
  
    # GET /products/new
    def new
      @product = authorize Product.new
      @categories = Category.all
    rescue Pundit::NotAuthorizedError
      flash[:notice] =  'Antes de criar um produto, crie uma categoria.'
      redirect_to action: :index
    end
  
    # GET /products/1/edit
    def edit
      @categories = Category.all
    end
  
    # POST /products or /products.json
    def create
      @product = Product.new(product_params)
  
      respond_to do |format|
        if @product.save
          format.html { redirect_to admin_products_path, notice: "Product was successfully created." }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /products/1 or /products/1.json
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admin_products_path, notice: "Product was successfully updated." }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /products/1 or /products/1.json
    def destroy
      @product.destroy
  
      respond_to do |format|
        format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def product_params
        params.require(:product).permit(:name, :description, :price, :publish, :category_id, :image)
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u| 
			u.permit(:name, :phone, :email, :password, :password_confirmation)
		end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id @category %>">
  <p>
    <strong>Nome:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Posição:</strong>
    <%= category.position %>
  </p>

</div>

app/views/admin/categories/_form.html.erb
<%= simple_form_for([:admin, @category]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :position %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1 class='h3 mb-0 text-gray-800 mb-4'>Editing category</h1>

<%= render "form", category: @category %>

app/views/admin/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 class='h3 mb-0 text-gray-800 mb-4'>Categorias</h1>
<div class="row">
	<div class="col-lg-12">
		<div class="card shadow mb-4">
			<div class="card-body">
        <table id="categories" class="table table-striped">
          <thead>
            <th>Nome</th>
            <th>Posição</th>
            <th>Opções</th>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td><%= category.position %></td>
                <td>
                  <div class="btn-group">
                    <%= button_to "Detalhes", admin_category_path(category), method: :get, class: "btn btn-sm btn-primary mr-2" %>
                    <%= button_to "Editar", edit_admin_category_path(category), method: :get, class: "btn btn-sm btn-warning mr-2" %>
                    <%= button_to "Excluir", admin_category_path(category), method: :delete, class: "btn btn-sm btn-danger mr-2" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to "Nova categoria", new_admin_category_path, class: 'btn btn-primary' %>
      </div>
		</div>
	</div>
</div>

app/views/admin/categories/new.html.erb
<h1 class='h3 mb-0 text-gray-800 mb-4'>Nova categoria</h1>

<%= render "form", category: @category %>

app/views/admin/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

app/views/admin/home/index.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
  <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
</div>
<div class="row">
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
              Earnings (Monthly)</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-calendar fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-success shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
              Earnings (Annual)</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks
            </div>
            <div class="row no-gutters align-items-center">
              <div class="col-auto">
                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
              </div>
              <div class="col">
                <div class="progress progress-sm mr-2">
                  <div class="progress-bar bg-info" role="progressbar"
                                                            style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                                            aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-warning shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
              Pending Requests</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-comments fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/_form.html.erb
<div class="row">
	<div class="col-lg-12">
		<div class="card shadow mb-4">
			<div class="card-body">
        <%= simple_form_for([:admin, @product]) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :image %>
            <%= f.input :price %>
            <%= f.input :publish %>
            <%= f.label :category_id, 'Categoria' %>
            <%= f.select(:category_id, options_for_select(Category.all.map { |c| [c.name, c.id] }, selected: @product.category_id), {}, { class: "form-control mb-4" }) %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, 'Salvar', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
		</div>
	</div>
</div>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id @product %>">
  <p>
    <strong>Nome:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Preço:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Publicado:</strong>
    <%= product.publish %>
  </p>

  <p>
    <strong>Imagem:</strong>
    <%= image_tag product.image.variant(:thumb) %>
  </p>

</div>

app/views/admin/products/edit.html.erb
<h1 class='h3 mb-0 text-gray-800 mb-4'>Editando produto</h1>

<%= render "form", product: @product %>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 class='h3 mb-0 text-gray-800 mb-4'>Produtos</h1>
<div class="row">
	<div class="col-lg-12">
		<div class="card shadow mb-4">
			<div class="card-body">
        <table id="products" class="table table-striped">
          <thead>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Publicado</th>
            <th>Opções</th>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td><%= product.name %></td>
                <td><%= product.description %></td>
                <td><%= product.price %></td>
                <td><%= product.publish %></td>
                <td>
                  <div class="btn-group">
                    <%= button_to "Detalhes", admin_product_path(product), method: :get, class: "btn btn-sm btn-primary mr-2" %>
                    <%= button_to "Editar", edit_admin_product_path(product), method: :get, class: "btn btn-sm btn-warning mr-2" %>
                    <%= button_to "Excluir", admin_product_path(product), method: :delete, class: "btn btn-sm btn-danger mr-2" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% if policy(:product).new? %>
          <%= link_to "Novo produto", new_admin_product_path, class: 'btn btn-primary' %>
        <% end %>
      </div>
		</div>
	</div>
</div>

app/views/admin/products/new.html.erb
<h1 class="h3 mb-0 text-gray-800 mb-4">Novo produto</h1>

<%= render "form", product: @product %>

app/views/admin/products/show.html.erb
<h1 class='h3 mb-0 text-gray-800 mb-4'>Detalhes do produto</h1>

<div class="row">
	<div class="col-lg-6">
		<div class="card shadow mb-4">
			<div class="card-body">
        <%= render @product %>
	    </div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<!-- Header-->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Shop in style</h1>
      <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
    </div>
  </div>
</header>
<!-- Section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% @products.each do |product| %>
        <div class="col mb-5">
          <div class="card h-100">
            <%= image_tag product.image.variant(:big_thumb) %>
            <div class="card-body p-4">
              <div class="text-center">
                <!-- Product name-->
                <h5 class="fw-bolder"><%= product.name %></h5>
                <!-- Product price-->
                <%= number_to_currency product.price %>
              </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
              <div class="text-center">
                <%= link_to 'Ver mais', admin_product_path(product), method: :get, class: "btn btn-outline-dark mt-auto" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin - Guga E-commerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag "admin", "data-turbo-track": "reload" %>
      <%= javascript_include_tag "admin", "data-turbo-track": "reload",
    defer: true %>
    </head>
    <body id="page-top">
      <div id="wrapper">
        
        <%= render 'layouts/admin/sidebar' %>
        
        <div id="content-wrapper" class="d-flex flex-column">
          <div id="content">
            <%= render 'layouts/admin/topbar' %>
            <div class="container-fluid">
              <%= yield %>
            </div>
          </div>
          
          <%= render 'layouts/admin/footer' %>
        
        </div>
      </div>
      <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
      </a>
    </body>
  </html>

app/views/layouts/admin/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Your Website 2021</span>
    </div>
  </div>
</footer>

app/views/layouts/admin/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= admin_root_path %>">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Gusta Admin</div>
  </a>
  <hr class="sidebar-divider my-0">
  <li class="nav-item active">
    <a class="nav-link" href="<%= admin_root_path %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>
  <hr class="sidebar-divider">
  <li class="nav-item">
    <a class="nav-link" href="<%= admin_categories_path %>">
      <i class="fa fa-bookmark"></i>
      <span>Categorias</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= admin_products_path %>">
      <i class="fa fa-box-open"></i>
      <span>Produtos</span>
    </a>
  </li>

  <li class="nav-item">
    <%= link_to(destroy_user_session_path, class: 'nav-link', data: { turbo_method: :delete }) do %>
      <i class="fa fa-arrow-alt-circle-left"></i>
      <span>Sair</span>
    <%end%>
  </li>

  <hr class="sidebar-divider d-none d-md-block">
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>

app/views/layouts/admin/_topbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>
  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">
    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Gusta</span>
        <%= image_tag 'undraw_profile.svg', class: "img-profile rounded-circle" %>
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
          Activity Log
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Logout
        </a>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <!-- Nav-->
    <%= render 'layouts/store/nav' %>
    <%= yield %>
    <!-- Footer-->
    <%= render 'layouts/store/footer' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gustavo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "devise", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "devise", "data-turbo-track": "reload",
    defer: true %>
  </head>

  <body>
    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6 text-center mb-5">
            <h2 class="heading-section"><%= link_to "Gustavo E-commerce", root_path %><h2>
          </div>
        </div>

        <div class="row justify-content-center">
          <div class="col-md-7 col-lg-5">
            <div class="login-wrap p-4 p-md-5">
              <%= render 'layouts/shared/flash' if flash.present?%>
              <div class="icon d-flex align-items-center justify-content-center">
                <span class="fa fa-user-o"></span>
              </div>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<div class="alert alert-info text-center">
	<% flash.each do |type, message| %>
		<div>
			<%= message %>
		</div>
	<% end %>
</div>

app/views/layouts/store/_footer.html.erb
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Gustavo E-commerce 2023</p>
  </div>
</footer>

app/views/layouts/store/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="#!">Guga E-commerce</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="<%= root_url %>">Home</a></li>
        <%= render 'layouts/store/user_signed_in' %>
      </ul>
      <form class="d-flex">
        <button class="btn btn-outline-dark" type="submit">
          <i class="bi-cart-fill me-1"></i>
          Cart
          <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
        </button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/store/_user_signed_in.html.erb
<% if user_signed_in? %>
  <li class="nav-item"><%= button_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
<% else %>
  <li class="nav-item"><%= link_to "Cadastre-se", new_user_registration_path, method: :get, class: "nav-link" %></li>
  <li class="nav-item"><%= link_to "Entrar", new_user_session_path, method: :get, class: "nav-link" %></li>
<% end %>